### ISSUE TITLE
A map become blank when an app resume.

### ISSUE THREAD

**Issue by gupuru** [moagrius/TileView#209]
Hi,

I tried your TileView v2.0.0 demo app.
When I start "Real Map", Everything is fine.
But if I pause and resume it, the map become blank like attached image.
Then I do action like scroll, the map become fine.

![20151025](https://cloud.githubusercontent.com/assets/7896734/10753230/debdb2ac-7cd2-11e5-979b-ed6b4343a1ec.png)

How can I redraw as soon as resuming?

Thanks.

**Comment by moagrius** [comment]
Probably needs an `invalidate` - I'll check it out.

**Comment by moagrius** [comment]
Actually was a little more complicated than that, and I needed to force the tile computation to recalculate on a `resume` - it's fixed now and available in the current version 2.0.1, both on gradle and pushed here.

thanks for catching that and posting

**Comment by gupuru** [comment]
I tried v2.0.1 and it was fixed.

Thanks.

**Comment by AndrazP** [comment]
The issue is still present in the latest version 2.1.1. 
I have tested it on multiple devices with Android versions from 4.2 to 6.0 and with your sample app.

**Comment by peterLaurence** [comment]
Weird. I don't have this issue. Which version of Android are you using?

**Comment by moagrius** [comment]
actually i am seeing it too, not on orientation change, but if you put the device to sleep then wake it up.  i'll work on a fix

**Comment by moagrius** [comment]
fixed in 2.1.2 (available now)

**Comment by AndrazP** [comment]
Can confirm it's fixed. Thanks!

**Comment by moagrius** [comment]
thanks for letting us know about the issue and the fix confirmation
